#!/bin/sh

usage() {
	echo "usage: git template add [<options>] <repo>"
	echo ""
	echo "add template submodule"
	echo ""
	echo "    -b <branch>           branch (master by default)"
	echo "    -h, --help            help"
	exit 1
}

main() {
	# sanity checks
	[ $# -lt 1 ] && usage
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkBasic
	checkTemplateNotExist

	# parse arg options
	local repository=
	local branch="master"
	# -
	OPTIND=1
	while getopts "b:" opt; do
		case "$opt" in
			b) branch="$OPTARG"
			;;
		esac
	done
	shift $((OPTIND-1))
	[ "$1" = "--" ] && shift
	local repository="$1"

	addTemplate $branch $repository 
}
main "$@"