#!/bin/sh

usage() {
	echo "usage: git template add [<options>] <repo>"
	echo ""
	echo "add template submodule"
	echo ""
	echo "    -b <branch>           branch (master by default)"
	echo "    -h, --help            help"
	exit 1
}

main() {
	# sanity checks
	[ $# -lt 1 ] && usage
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkBasic
	checkAlreadyExist

	# parse arg options
	local repository=
	local branch_option="-b master"
	# -
	OPTIND=1
	while getopts "b:" opt; do
		case "$opt" in
			b) branch_option="-b $OPTARG"
			;;
		esac
	done
	shift $((OPTIND-1))
	[ "$1" = "--" ] && shift
	local repository="$1"

	# add submodule
	git submodule add $branch_option $repository $DEFINE_TEMPLATE_PATH
	if [ ! $? -eq 0 ]; then
		delete
		exit 1
	fi

	echo "done"
}
main "$@"