#!/bin/sh

usage() {
cat << EOM >&2
usage: git template apply

Apply template to current project

    -h, --help            help
EOM
exit 1
}

main() {
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	local wasLocked=0
	isLocked && wasLocked=1
	lockTemplate
	unlockTemplate
	cd "$DEFINE_TEMPLATE_GITPATH"
	# --

	# 0- Prepare a temporary config file
	mkdir -p "$DEFINE_TEMPLATE_TMP"
	touch "$DEFINE_TEMPLATE_TMP_CONFIG"
	#perl "$GITTEMPLATE_DIR/common/copyTmp2Config.pl" \
	#	 "$DEFINE_TEMPLATE_INSTANCE_CONFIG" "$DEFINE_TEMPLATE_TMP_CONFIG" \
	#	 "replacement"
	# 1- get file list
	find "$DEFINE_TEMPLATE_GITPATH" > "$DEFINE_TEMPLATE_PARSEFILE_SRC"
	perl "$GITTEMPLATE_DIR/common/parseFile.pl" "$DEFINE_TEMPLATE_PARSEFILE_SRC"
	# 2- ...
	# copy replacement section in config file
	perl "$GITTEMPLATE_DIR/common/copyTmp2Config.pl" \
		 "$DEFINE_TEMPLATE_TMP_CONFIG" "$DEFINE_TEMPLATE_INSTANCE_CONFIG" \
		 "replacement"

	# restore lock state
	rm -rf "$DEFINE_TEMPLATE_TMP"
	[ $wasLocked == 1 ] && lockTemplate
}

main "$@"