#!/bin/sh

usage() {
	git commit -h 2>&1 | sed 's/usage\:\ git/usage\:\ git template/g' >&2
	exit 1
}

main() {
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	unlockTemplate
	cd "$DEFINE_TEMPLATE_GITPATH"
	git commit "$@"
}
main "$@"