#!/bin/sh

usage() {
	git commit -h 2>&1 | sed 's/usage\:\ git/usage\:\ git template/g' >&2
	exit 1
}

main() {
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	local wasLocked=0
	isLocked && wasLocked=1
	# git commit
	unlockTemplate
	cd "$DEFINE_TEMPLATE_GITPATH"
	git commit "$@"
	# restore lock state
	[ $wasLocked == 1 ] && lockTemplate
}
main "$@"