#!/bin/sh

usage() {
cat << EOM >&2
usage: git template config [options] <key> [value]

get or set a template key

Options

    -l, --list            list all
    -e, --edit            open an editor
    -u, --unset           remove a key
    -h, --help            help

Example:
    git template config core.sha
    git template config core.sha master
EOM
exit 1
}

editor() {
	local ed=$(git config core.editor)
	if [ -z "$ed" ]; then
		echo No editor configured
		exit 1
	fi
	$ed $DEFINE_TEMPLATE_INSTANCE_CONFIG
	exit 0
}

main() {
	[[ -z "$@" ]] && usage
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	local re='-+e(dit)?(\ |$)'; [[ "$@" =~ $re ]] && editor
	checkTemplateExist
	perl "$GITTEMPLATE_DIR/common/config.pl" "$@"
}

main "$@"