#!/bin/sh

usage() {
	echo "usage: git template lock"
	echo ""
	echo "lock template to any changes"
	echo "see also 'unlock'"
	echo ""
	echo "    -h, --help            help"
	exit 1
}

main() {
	# sanity checks
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	lockTemplate
}

main "$@"