#!/bin/sh

usage() {
cat << EOM >&2
usage: git template lock

Forbid any template edition (this is the default state)
see also 'unlock'

    -h, --help            help
EOM
exit 1
}

main() {
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	lockTemplate
}

main "$@"