#!/bin/sh

usage() {
cat << EOM >&2
usage: git template remove

remove template

    -h, --help            help
EOM
exit 1
}

main() {
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	rm -rf $DEFINE_TEMPLATE_ROOTPATH
	exit 0
}

main "$@"