#!/bin/sh

usage() {
	echo "usage: git template remove [<options>]"
	echo ""
	echo "remove template submodule"
	echo ""
	echo "    -h, --help            help"
	exit 1
}

main() {
	# sanity checks
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkBasic
	
	# deletion
	delete
}

main "$@"