#!/bin/sh

usage() {
	echo "usage: git template unlock"
	echo ""
	echo "unlock template to allow changes"
	echo "see also 'lock'"
	echo ""
	echo "    -h, --help            help"
	exit 1
}

main() {
	# sanity checks
	local re='-+h(elp)?(\ |$)'; [[ "$@" =~ $re ]] && usage
	checkTemplateExist
	unlockTemplate
}

main "$@"